//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ajuma.Relationship_Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDonDatHang
    {
        public string madondathang { get; set; }
        public string masanpham { get; set; }
        public double soluong { get; set; }
        public double dongia { get; set; }
        public Nullable<double> giamgia { get; set; }
        public Nullable<double> trongluong { get; set; }
        public Nullable<double> thanhtien { get; set; }
    
        public virtual DonDatHang DonDatHang { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
