//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ajuma.Relationship_Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.ChiTietDonDatHangs = new HashSet<ChiTietDonDatHang>();
            this.ChiTietDonNhapHangs = new HashSet<ChiTietDonNhapHang>();
        }
    
        public string masanpham { get; set; }
        public string tensanpham { get; set; }
        public System.DateTime ngayphathanh { get; set; }
        public string phienban { get; set; }
        public Nullable<double> trongluong { get; set; }
        public Nullable<double> dongianhap { get; set; }
        public double dongiaban { get; set; }
        public double soluongkho { get; set; }
        public string trangthai { get; set; }
        public string mota { get; set; }
        public string manhacungcap { get; set; }
        public string matheloai { get; set; }
        public string maalbum { get; set; }
        public string anh { get; set; }
    
        public virtual Album Album { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonDatHang> ChiTietDonDatHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonNhapHang> ChiTietDonNhapHangs { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
        public virtual TheLoai TheLoai { get; set; }
    }
}
