//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ajuma.Relationship_Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class XaPhuong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public XaPhuong()
        {
            this.KhachHangs = new HashSet<KhachHang>();
        }
    
        public int maxaphuong { get; set; }
        public int maquanhuyen { get; set; }
        public string tenxaphuong { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhachHang> KhachHangs { get; set; }
        public virtual QuanHuyen QuanHuyen { get; set; }
    }
}
